lec 1

ZT

In [1]:
#Import the NumPy library
import numpy as np
# Import the Pandas library
import pandas as pd

Follow CQ's example.

Boston housing is no long available in sklearn. We will use the following California dataset instead.

In [2]:
from sklearn.datasets import fetch_california_housing
import statsmodels.formula.api as smf
df = fetch_california_housing()

In [3]:
dir(df)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [4]:
type(df)

sklearn.utils._bunch.Bunch

In [5]:
CA = pd.DataFrame(df.data, columns=df.feature_names)

In [6]:
CA.head

<bound method NDFrame.head of        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Lo

In [7]:
CA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


In [15]:
Y = df.target
Y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

Perhaps the idea of modeling use *formula* is also outdated. As a theorist myself, I don't try many models.
The formula is some historic relic from R.
And the modern approach is just specify X and Y. 

In [16]:
model = smf.ols(formula='Y ~ MedInc + HouseAge', data=CA)

In [17]:
result = model.fit()

In [18]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.509
Model:                            OLS   Adj. R-squared:                  0.509
Method:                 Least Squares   F-statistic:                 1.070e+04
Date:                Tue, 08 Aug 2023   Prob (F-statistic):               0.00
Time:                        22:32:35   Log-Likelihood:                -24899.
No. Observations:               20640   AIC:                         4.980e+04
Df Residuals:                   20637   BIC:                         4.983e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.1019      0.019     -5.320      0.000      -0.139      -0.064
MedInc         0.4317      0.003    144.689      0.000       0.426       0.438
HouseAge       0.0174      0.000     38.726      0.000       0.017       0.018
==============================================================================
Omnibus:                     4099.868   Durbin-Watson:                   0.787
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9707.077
Skew:                           1.118   Prob(JB):                         0.00
Kurtosis:                       5.507   Cond. No.                         108.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
result.params

Intercept   -0.101890
MedInc       0.431692
HouseAge     0.017441
dtype: float64

An alternative way to run OLS.

This is less convenient in terms of modeling

In [34]:
CA['const'] = 1
X = CA[['const', 'MedInc','HouseAge']]

In [35]:
import statsmodels.api as sm
model = sm.OLS(Y, X)

In [36]:
result = model.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.509
Model:                            OLS   Adj. R-squared:                  0.509
Method:                 Least Squares   F-statistic:                 1.070e+04
Date:                Tue, 08 Aug 2023   Prob (F-statistic):               0.00
Time:                        22:41:39   Log-Likelihood:                -24899.
No. Observations:               20640   AIC:                         4.980e+04
Df Residuals:                   20637   BIC:                         4.983e+04
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1019      0.019     -5.320      0.000      -0.139      -0.064
MedInc         0.4317      0.003    144.689      0.000       0.426       0.438
HouseAge       0.0174      0.000     38.726      0.000       0.017       0.018
==============================================================================
Omnibus:                     4099.868   Durbin-Watson:                   0.787
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9707.077
Skew:                           1.118   Prob(JB):                         0.00
Kurtosis:                       5.507   Cond. No.                         108.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Sampling splitting


In [37]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [47]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=88)

In [48]:
X_train.shape

(16512, 3)

In [45]:
X_test.shape

(4128, 3)

In [50]:
X_train

const   MedInc  HouseAge
14429      1   3.0774      27.0
10835      1   4.4732      25.0
13591      1   0.7075      35.0
18472      1   2.4821      17.0
18743      1   2.5592      16.0
...      ...      ...       ...
8033       1   3.2024      43.0
9790       1   2.6094      20.0
2481       1   2.1458      29.0
4047       1  12.8879      28.0
6432       1   4.5491      43.0

[16512 rows x 3 columns]

In [54]:
model = LinearRegression( )
model.fit(X_train, Y_train)


LinearRegression()

In [52]:
model.coef_

array([0.        , 0.4305967 , 0.01762738])

Score for OLS is the same as $R^2$

In [56]:
model.score(X_test, Y_test)

0.5004318279591309

K-fold cross validation

In [62]:
from sklearn.model_selection import KFold, cross_val_score

In [58]:
X, y = fetch_california_housing(return_X_y=True)

In [59]:
model = LinearRegression()

In [60]:
kfold = KFold(n_splits=5, shuffle=True, random_state=0)

In [65]:
scores = cross_val_score(model, X, y, cv=kfold )

In [66]:
scores

array([0.59432327, 0.60293778, 0.60235253, 0.60066293, 0.61828258])